using Go = import "../../zombiezen/go-capnproto2/go.capnp";
@0xdbb9ad1f14bf0b37;  # unique file ID, generated by `capnp id`
$Go.package("data");
$Go.import("data/programmer");


struct Programmer {
  name @0 :Text;
  email @1 :Text;
  likes @2 :List(Text);

}

